SEED : 42 # Set seed for reproducibility
DEVICE_str : cpu
dataset : nsl-kdd
dataset_type : nids
model : ml

# train_test_split : 0.8

run_type : 'train' # 'train' or 'test'

plots_dir: '../artifacts/plots' # Directory for results
models_dir: '../artifacts/models/' # Directory for storing models

dataset_dir: '../nsl-kdd/NSL-KDD/' # Directory for dataset
scaler_dir : '../artifacts/scaler' # Directory for scaler data

batch_size : 32

# Columns
columns:
  - duration
  - protocol_type
  - service
  - flag
  - src_bytes
  - dst_bytes
  - land
  - wrong_fragment
  - urgent
  - hot
  - num_failed_logins
  - logged_in
  - num_compromised
  - root_shell
  - su_attempted
  - num_root
  - num_file_creations
  - num_shells
  - num_access_files
  - num_outbound_cmds
  - is_hot_login
  - is_guest_login
  - count
  - srv_count
  - serror_rate
  - srv_serror_rate
  - rerror_rate
  - srv_rerror_rate
  - same_srv_rate
  - diff_srv_rate
  - srv_diff_host_rate
  - dst_host_count
  - dst_host_srv_count
  - dst_host_same_srv_rate
  - dst_host_diff_srv_rate
  - dst_host_same_src_port_rate
  - dst_host_srv_diff_host_rate
  - dst_host_serror_rate
  - dst_host_srv_serror_rate
  - dst_host_rerror_rate
  - dst_host_srv_rerror_rate
  - attack_type
  - difficulty_score

categorical_columns:
  - protocol_type
  - service
  - flag

binary_columns:
  - land
  - logged_in
  - root_shell
  - su_attempted
  - is_hot_login
  - is_guest_login


redundant_col: difficulty_score

target_col: attack_type

ml_models :
   'Naïve Bayes Classifier': GaussianNB
   'Bernoulli Naïve Bayes Classifier': BernoulliNB
   'Decision Tree Classifier' : DecisionTreeClassifier 
   'KNN Classifier': KNeighborsClassifier
   'Random Forest Classifier': RandomForestClassifier
   'Logistic Regression': LogisticRegression
    # 'Support Vector Classifier': SVC, 'Linear Regression': LinearRegression


